In [1]:
import pandas as pd
import numpy as np

**Pandas GroupBy**

In [2]:
df = pd.read_csv("student_data.csv")
df["Total"] = df.iloc[:,2:5].sum(axis=1)
df.drop(columns=["Data Structure Marks","Algorithm Marks","Python Marks","EnrollmentDate"],inplace=True)
df.loc[df["Total"]<=200,"Total"] = np.nan
df["CompletionStatus"] = "Completed"
df

   StudentID          FullName CompletionStatus Instructor    Location  Total
0     PH1001       Alif Rahman        Completed  Mr. Karim       Dhaka  258.0
1     PH1002     Fatima Akhter        Completed  Ms. Salma  Chattogram    NaN
2     PH1003     Imran Hossain        Completed  Mr. Karim       Dhaka  261.0
3     PH1004  Jannatul Ferdous        Completed  Ms. Salma      Sylhet  238.0
4     PH1005       Kamal Uddin        Completed  Mr. Karim  Chattogram    NaN
5     PH1006       Laila Begum        Completed  Ms. Salma    Rajshahi  228.0
6     PH1007    Mahmudul Hasan        Completed  Mr. Karim       Dhaka    NaN
7     PH1008       Nadia Islam        Completed  Ms. Salma  Chattogram  247.0
8     PH1009        Omar Faruq        Completed  Mr. David       Dhaka  220.0
9     PH1010      Priya Sharma        Completed  Ms. Salma      Sylhet  266.0
10    PH1011      Rahim Sheikh        Completed  Mr. Karim      Khulna    NaN
11    PH1012   Sadia Chowdhury        Completed  Ms. Salma  Chattogram  257.0
12    PH1013      Tanvir Ahmed        Completed  Mr. David       Dhaka  229.0
13    PH1014        Urmi Akter        Completed  Ms. Salma    Rajshahi    NaN
14    PH1015      Wahiduzzaman        Completed  Mr. Karim       Dhaka  256.0
15    PH1016      Ziaur Rahman        Completed  Ms. Salma  Chattogram    NaN
16    PH1017       Afsana Mimi        Completed  Mr. Karim       Dhaka  273.0
17    PH1018       Babul Ahmed        Completed  Ms. Salma      Sylhet  261.0
18    PH1019      Faria Rahman        Completed  Mr. David  Chattogram    NaN
19    PH1020        Nasir Khan        Completed  Ms. Salma       Dhaka  261.0

In [3]:
instructor_group = df.groupby("Instructor")
instructor_group

In [4]:
instructor_group.describe()

           Total
           count        mean        std    min     25%    50%     75%    max
Instructor
Mr. David    2.0  224.500000   6.363961  220.0  222.25  224.5  226.75  229.0
Mr. Karim    4.0  262.000000   7.615773  256.0  257.50  259.5  264.00  273.0
Ms. Salma    7.0  251.142857  13.993196  228.0  242.50  257.0  261.00  266.0

In [5]:
instructor_group["Total"].mean()

Instructor
Mr. David    224.500000
Mr. Karim    262.000000
Ms. Salma    251.142857
Name: Total, dtype: float64

In [6]:
df["Total"] = df["Total"].fillna(df["Instructor"].map(instructor_group["Total"].mean()))
df

,StudentID,FullName,CompletionStatus,Instructor,Location,Total
0,PH1001,Alif Rahman,Completed,Mr. Karim,Dhaka,258.000000
1,PH1002,Fatima Akhter,Completed,Ms. Salma,Chattogram,251.142857
2,PH1003,Imran Hossain,Completed,Mr. Karim,Dhaka,261.000000
3,PH1004,Jannatul Ferdous,Completed,Ms. Salma,Sylhet,238.000000
4,PH1005,Kamal Uddin,Completed,Mr. Karim,Chattogram,262.000000
5,PH1006,Laila Begum,Completed,Ms. Salma,Rajshahi,228.000000
6,PH1007,Mahmudul Hasan,Completed,Mr. Karim,Dhaka,262.000000
7,PH1008,Nadia Islam,Completed,Ms. Salma,Chattogram,247.000000
8,PH1009,Omar Faruq,Completed,Mr. David,Dhaka,220.000000
9,PH1010,Priya Sharma,Completed,Ms. Salma,Sylhet,266.000000
10,PH1011,Rahim Sheikh,Completed,Mr. Karim,Khulna,262.000000
11,PH1012,Sadia Chowdhury,Completed,Ms. Salma,Chattogram,257.000000
12,PH1013,Tanvir Ahmed,Completed,Mr. David,Dhaka,229.000000
13,PH1014,Urmi Akter,Completed,Ms. Salma,Rajshahi,251.142857
14,PH1015,Wahiduzzaman,Completed,Mr. Karim,Dhaka,256.000000
15,PH1016,Ziaur Rahman,Completed,Ms. Salma,Chattogram,251.142857
16,PH1017,Afsana Mimi,Completed,Mr. Karim,Dhaka,273.000000
17,PH1018,Babul Ahmed,Completed,Ms. Salma,Sylhet,261.000000
18,PH1019,Faria Rahman,Completed,Mr. David,Chattogram,224.500000
19,PH1020,Nasir Khan,Completed,Ms. Salma,Dhaka,261.000000